services:
  postgres:
    image: 'postgres:17-alpine'
    container_name: coupon-manager-postgres
    environment:
      - 'POSTGRES_DB=coupon_manager'
      - 'POSTGRES_USER=coupon_manager'
      - 'POSTGRES_PASSWORD=coupon_manager'
    ports:
      - '5432:5432'
    volumes:
      - coupon-manager-postgres-data:/var/lib/postgresql/data

volumes:
  coupon-manager-postgres-data:
