CREATE TABLE coupons
(
    id             UUID                        NOT NULL,
    code           VARCHAR(100)                NOT NULL,
    created_at     TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    max_uses       INTEGER                     NOT NULL,
    current_uses   INTEGER                     NOT NULL,
    target_country VARCHAR(2)                  NOT NULL,

    CONSTRAINT pk_coupons PRIMARY KEY (id),
    CONSTRAINT uk_coupons_code UNIQUE (code),
    CONSTRAINT chk_coupons_max_uses_positive CHECK (max_uses > 0),
    CONSTRAINT chk_coupons_current_uses_non_negative CHECK (current_uses >= 0),
    CONSTRAINT chk_coupons_current_uses_not_greater_than_max CHECK (current_uses <= max_uses)
);

CREATE TABLE coupon_usages
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    coupon_id UUID                                NOT NULL,
    user_id   VARCHAR(200)                        NOT NULL,
    used_at   TIMESTAMP WITHOUT TIME ZONE         NOT NULL,

    CONSTRAINT pk_coupon_usages PRIMARY KEY (id),
    CONSTRAINT fk_coupon_usages_coupon FOREIGN KEY (coupon_id) REFERENCES coupons (id),
    CONSTRAINT uk_coupon_usages_coupon_id_user_id UNIQUE (coupon_id, user_id)
);

CREATE INDEX idx_coupon_usages_coupon_id ON coupon_usages (coupon_id);
CREATE INDEX idx_coupon_usages_user_id ON coupon_usages (user_id);